name       : solaar
version    : 1.0.7
release    : 13
source     :
    - git|https://github.com/pwr-Solaar/Solaar : 1.0.7
license    : GPL-2.0-or-later
homepage   : https://pwr-solaar.github.io/Solaar/
component  : system.utils
summary    : Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
description: |
    Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-gobject
    - python3-pyudev
    - python-psutil
    - python-xlib
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-wake-notifications.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 rules.d/42-logitech-unify-permissions.rules $installdir/etc/udev/rules.d/42-logitech-unify-permissions.rules
    install -D -m 00644 share/autostart/solaar.desktop $installdir/usr/share/xdg/autostart/solaar.desktop
