name       : solaar
version    : 0.9.2
release    : 1
source     :
    - https://github.com/pwr/Solaar/archive/0.9.2.tar.gz : b2802812e5aafae4801692ac8cf8a11e9f46f2adc43522d977ef35257e7ea424
license    : GPL-2.0
component  : system.utils
summary    : Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
description: |
    Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python3-gobject
    - python3-pyudev
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 rules.d/42-logitech-unify-permissions.rules $installdir/etc/udev/rules.d/42-logitech-unify-permissions.rules