name       : solaar
version    : 1.1.7
release    : 21
source     :
    - https://github.com/pwr-Solaar/Solaar/archive/refs/tags/1.1.7.tar.gz : f495ec6814b92d5401580cfe8b273a9abc180c78150be9f8e7540cb7c48a9ed1
license    : GPL-2.0-or-later
homepage   : https://pwr-solaar.github.io/Solaar/
component  : system.utils
summary    : Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
description: |
    Solaar is a Linux device manager for Logitech's Unifying Receiver peripherals.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-evdev
    - python-gobject
    - python-psutil
    - python-xlib
    - python3-pyudev
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 rules.d/42-logitech-unify-permissions.rules $installdir/etc/udev/rules.d/42-logitech-unify-permissions.rules
    install -D -m 00644 share/autostart/solaar.desktop $installdir/usr/share/xdg/autostart/solaar.desktop
